site_name: Nayami's Blog
# site_description: OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛
site_description: 安逐悲的博客
site_author: 安逐悲
# site_url: https://oi-wiki.org
strict: false
# Repository
repo_name: "NayamiOR/Nayami's Blog"
repo_url: 'https://github.com/NayamiOR/nayamis-blog'

theme:
  name: material
  logo: assets/OR-icon.png
  font:
    text: 'Fira Sans'
    code: 'Fira Mono, Jetbrains Mono'
  # custom_dir: 'mkdocs-material/material'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
  plugins: []
nav:
  - Home: index.md
  - 热身:
    - Git安装: git-install.md
    - 学习资料:
      - Python: python-materials.md
  - 基础知识: 
    - 类C语言基本语法介绍: 类C语言基本语法介绍.md