site_name: Nayami's Blog
site_description: 安逐悲的博客
site_author: 安逐悲
strict: false
# Repository
repo_name: "NayamiOR/Nayami's Blog"
repo_url: 'https://github.com/NayamiOR/nayamis-blog'

theme:
  # name: null
  name: material
  logo: assets/OR-icon.png
  font:
    text: 'Fira Sans'
    code: 'Fira Mono, Jetbrains Mono'
  # custom_dir: 'mkdocs-material/material'
  # static_templates:
  #   - 404.html

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
  plugins: []

nav:
  - Home: index.md
  - 热身:
    - Git安装: git-install.md
    - 学习资料:
      - Python: python-materials.md
  - 基础知识: 
    - 类C语言基本语法介绍: 类C语言基本语法介绍.md
  # - 算法笔记:
  
  - 杂记:
    - 论Java和C#在基础语法上的相似度: Java-and-csharp.md
    - 我自用的二分查找算法推荐: my-binary.md