site_name: Nayami's Blog
site_description: 安逐悲的博客
site_author: 安逐悲
strict: false
# Repository
repo_name: "NayamiOR/Nayami's Blog"
repo_url: "https://github.com/NayamiOR/nayamis-blog"
dev_addr: "127.0.0.1:18080"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  logo: assets/OR-icon.png
  favicon: assets/OR-icon.png
  font:
    text: "Fira Sans"
    code: "Fira Mono, Jetbrains Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue

      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
  plugins: []

extra_css:
  - assets/extra.css

nav:
  - Home: index.md
  - 基础知识:
      - 基础知识简介: Base/index.md
      - 类C语言基本语法介绍: Base/类C语言基本语法介绍.md
      - Git安装: Base/git-install.md
  - 编程语言:
      - 编程语言简介: Programming/index.md
      - Rust:
          - Rust 新手引路: Programming/Rust/新手引路.md
          - 全知识点目录: Programming/Rust/全知识点目录.md
          - Clone 和 Copy Trait 的区别: Programming/Rust/Clone 和 Copy trait的区别.md
          - 为什么 & 怎么在 Rust 中避免使用引用: Programming/Rust/为什么 & 怎么在rust中避免使用引用.md
          - Rust 字符串类型转换: Programming/Rust/Rust 字符串类型转换.md
      - Go:
          - 在 Go 中使用路由（基础）: Programming/Golang/在Go中使用路由.md
          - Go 进阶语法: Programming/Golang/Go进阶语法.md
          - Go Web 学习路线 & 资源: Programming/Golang/Go_Web学习路线_资源.md
      - Python:
          - Python 学习指北: Programming/Python/python-materials.md
      - 指针、引用和类导论（Beta版）: Programming/Skills/ptr-ref-class (Beta).md
  - 算法:
      - 算法简介: Algo/index.md
      - 算法竞赛入门大纲（蓝桥向）: Algo/introHandBook-LanQiao.md
      - 算法入门题单: Algo/algo-checklist.md
      - 算法入门必备知识：复杂度: Algo/complexity.md
      - 二分查找: Algo/my-binary.md
      - Codeforces 常用数学知识: Algo/CF-math.md
  - 计算机科学:
      - 计算机科学简介: CS/index.md
      - 知乎：自学计算机优先级顺序: CS/自学计算机优先级顺序.md
